// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5-H_o2GHtx3TpAGyhDoVDoOYUntsSAxI',
    appId: '1:906535310231:web:cdc157748a3e22d97dead2',
    messagingSenderId: '906535310231',
    projectId: 'wathsapp-620cf',
    authDomain: 'wathsapp-620cf.firebaseapp.com',
    storageBucket: 'wathsapp-620cf.appspot.com',
    measurementId: 'G-QP10QBC9JF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMPBAWQh1pGUUTA7apJ1zzf6lrSsF4snw',
    appId: '1:906535310231:android:54bb27084897e6597dead2',
    messagingSenderId: '906535310231',
    projectId: 'wathsapp-620cf',
    storageBucket: 'wathsapp-620cf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0V6InHdpEFMZ16HSbUsvQMB-RIf940Ow',
    appId: '1:906535310231:ios:fa84c78a034d93007dead2',
    messagingSenderId: '906535310231',
    projectId: 'wathsapp-620cf',
    storageBucket: 'wathsapp-620cf.appspot.com',
    iosBundleId: 'com.example.wathsappFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0V6InHdpEFMZ16HSbUsvQMB-RIf940Ow',
    appId: '1:906535310231:ios:b8b1d212da5107177dead2',
    messagingSenderId: '906535310231',
    projectId: 'wathsapp-620cf',
    storageBucket: 'wathsapp-620cf.appspot.com',
    iosBundleId: 'com.example.wathsappFlutter.RunnerTests',
  );
}
